import { BlockConfig, ScenarioBlock } from '@/store/useAppStore';
import { CITY_THEME } from './cityMappings';

const GRID = CITY_THEME.gridSize;

type BlueprintNode = {
  label: string;
  type: ScenarioBlock['type'];
  offset?: { x: number; y: number };
  footprint?: { widthUnits: number; heightUnits: number };
  visual?: BlockConfig['visual'];
  config?: Partial<BlockConfig>;
};

export type CityBlueprint = {
  key: string;
  title: string;
  description: string;
  primaryType: ScenarioBlock['type'];
  primaryNodeIndex: number;
  nodes: BlueprintNode[];
  localConnections?: Array<{ from: number; to: number }>;
  clusterLabel?: string;
  exposed?: boolean;
};

const perimeterVisual = {
  background: '#D9C7A5',
  border: '#B28D66',
  opacity: 0.85,
  pattern: 'perimeter' as const,
};

const riskChipVisual = {
  background: '#EFDCC2',
  border: '#C9A980',
  opacity: 0.9,
};

const darkProcessVisual = (base: string) => ({
  background: base,
  border: '#111111',
  opacity: 0.95,
  pattern: 'grid' as const,
});

export const CITY_BLUEPRINTS: Record<string, CityBlueprint> = {
  'input-personal': {
    key: 'input-personal',
    title: 'Quartiere Dati Personali',
    description: 'Anagrafiche, CRM, account.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Residenza Dati',
    nodes: [
      {
        label: 'Dati Personali',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#5E8B4B',
          border: '#314A25',
          opacity: 0.95,
          pattern: 'grid',
        },
        config: { dataTypes: ['Identificativi'] },
      },
      {
        label: 'Perimetro Consenso',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.5, y: 1.2 },
        visual: perimeterVisual,
      },
      {
        label: 'Audit Trail',
        type: 'risk',
        footprint: { widthUnits: 1.8, heightUnits: 0.45 },
        offset: { x: 4.6, y: -0.3 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 0, to: 2 },
    ],
  },
  'input-video': {
    key: 'input-video',
    title: 'Sorveglianza / Video',
    description: 'CCTV, bodycam, feed live.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Nodo Sorveglianza',
    nodes: [
      {
        label: 'Video / Immagini',
        type: 'input',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#4A6F3B',
          border: '#253919',
          pattern: 'grid',
          opacity: 0.95,
        },
        config: { dataTypes: ['Biometrici'] },
      },
      {
        label: 'Perimetro Biometria',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: perimeterVisual,
      },
      {
        label: 'Buffer Volatile',
        type: 'risk',
        footprint: { widthUnits: 2.2, heightUnits: 0.5 },
        offset: { x: 5.2, y: -0.2 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 0, to: 2 },
    ],
  },
  'input-public': {
    key: 'input-public',
    title: 'Open & Pubblici',
    description: 'Dataset aperti, scraping.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Biblioteca',
    nodes: [
      {
        label: 'Dati Pubblici',
        type: 'input',
        footprint: { widthUnits: 4, heightUnits: 0.7 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#73A560',
          border: '#406230',
          pattern: 'grid',
          opacity: 0.9,
        },
      },
      {
        label: 'Licenze & Attribution',
        type: 'risk',
        footprint: { widthUnits: 2.5, heightUnits: 0.45 },
        offset: { x: 4.1, y: -0.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-operational': {
    key: 'input-operational',
    title: 'Dati Operativi / IoT',
    description: 'Log tecnici, sensori, macchinari.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Operational Data',
    nodes: [
      {
        label: 'Log Operativi',
        type: 'input',
        footprint: { widthUnits: 4, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#4C7A5A',
          border: '#2F4F37',
          pattern: 'grid',
          opacity: 0.95,
        },
      },
      {
        label: 'Sensori / IoT',
        type: 'input',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: {
          background: '#6AA37A',
          border: '#326243',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-partner': {
    key: 'input-partner',
    title: 'Dataset di Partner',
    description: 'Dati acquistati o ricevuti da terzi.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Partner Data',
    nodes: [
      {
        label: 'Dati Fornitori',
        type: 'input',
        footprint: { widthUnits: 4, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#5AA6A9',
          border: '#2B6F72',
          pattern: 'grid',
          opacity: 0.95,
        },
      },
      {
        label: 'Accordi & SLA',
        type: 'risk',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-llm': {
    key: 'process-llm',
    title: 'Fabbrica LLM',
    description: 'Core AI, orchestratori.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Fabbrica LLM',
    nodes: [
      {
        label: 'LLM Core',
        type: 'process',
        footprint: { widthUnits: 5.5, heightUnits: 1 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#2F2F2F'),
        config: { aiModel: 'LLM' },
      },
      {
        label: 'Prompt Guard',
        type: 'risk',
        footprint: { widthUnits: 2.2, heightUnits: 0.45 },
        offset: { x: 5.6, y: 0.1 },
        visual: riskChipVisual,
      },
      {
        label: 'Dataset Ombra',
        type: 'risk',
        footprint: { widthUnits: 2.5, heightUnits: 0.5 },
        offset: { x: -0.6, y: -0.9 },
        visual: {
          background: '#3C3C3C',
          border: '#1E1E1E',
          opacity: 0.8,
          pattern: 'dots',
        },
      },
    ],
    localConnections: [
      { from: 2, to: 0 },
      { from: 0, to: 1 },
    ],
  },
  'process-biometric': {
    key: 'process-biometric',
    title: 'Laboratorio Biometrico',
    description: 'Matching, riconoscimento.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Analisi Biometrica',
        type: 'process',
        footprint: { widthUnits: 4.5, heightUnits: 1 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#3F3F3F'),
      },
      {
        label: 'Supervisione Umana',
        type: 'risk',
        footprint: { widthUnits: 2, heightUnits: 0.5 },
        offset: { x: 4.8, y: -0.2 },
        visual: riskChipVisual,
        config: { humanInTheLoop: true },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-rag': {
    key: 'process-rag',
    title: 'Centro RAG',
    description: 'Retrieval + context injection.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Motore RAG',
        type: 'process',
        footprint: { widthUnits: 4, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#4A4A4A'),
      },
      {
        label: 'Indice Embedding',
        type: 'storage',
        footprint: { widthUnits: 3.5, heightUnits: 0.6 },
        offset: { x: 0, y: 1.1 },
        visual: {
          background: '#B87EEA',
          border: '#8046AA',
          opacity: 0.9,
        },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-automation': {
    key: 'process-automation',
    title: 'Automazione / Regole',
    description: 'Motori deterministici e scoring tradizionale.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Motore di Regole',
        type: 'process',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#6D28D9'),
      },
      {
        label: 'Tabella Scoring',
        type: 'impact',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: {
          background: '#DDD6FE',
          border: '#6D28D9',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-modelops': {
    key: 'process-modelops',
    title: 'Training / MLOps',
    description: 'Pipeline di addestramento e monitoraggio.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Pipeline Training',
        type: 'process',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#7C3AED'),
      },
      {
        label: 'Monitoraggio Modelli',
        type: 'risk',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'storage-eu': {
    key: 'storage-eu',
    title: 'Vault Europeo',
    description: 'Cluster EU resilienti.',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Vault Dati (UE)',
        type: 'storage',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#C77DFF',
          border: '#8A4DB8',
          opacity: 0.9,
        },
      },
      {
        label: 'Perimetro BYOK',
        type: 'risk',
        footprint: { widthUnits: 5.2, heightUnits: 0.55 },
        offset: { x: -0.3, y: 1 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'storage-us': {
    key: 'storage-us',
    title: 'Porto Franco (USA)',
    description: 'Servizi fuori UE.',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Cloud (USA)',
        type: 'storage',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#E0AAFF',
          border: '#9A6DB8',
          opacity: 0.9,
        },
      },
      {
        label: 'Supervisione Transfer',
        type: 'risk',
        footprint: { widthUnits: 2.4, heightUnits: 0.5 },
        offset: { x: 4.7, y: -0.2 },
        visual: {
          background: '#F0C9C9',
          border: '#C87A7A',
          opacity: 0.95,
        },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'storage-onprem': {
    key: 'storage-onprem',
    title: 'Infrastruttura On-Premise',
    description: 'Server proprietari o device edge.',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Server Proprietari',
        type: 'storage',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6B7280',
          border: '#4B5563',
          opacity: 0.9,
        },
      },
      {
        label: 'Ridondanza Locale',
        type: 'risk',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'output-decision': {
    key: 'output-decision',
    title: 'Decisione Automatizzata',
    description: 'Comitati digitali, scoring.',
    primaryType: 'output',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Decisione Automatica',
        type: 'output',
        footprint: { widthUnits: 4, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#D65D5D',
          border: '#8A2D2D',
          opacity: 0.95,
        },
      },
      {
        label: 'Supervisione Umana',
        type: 'risk',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0, y: 1.1 },
        visual: perimeterVisual,
        config: { humanInTheLoop: true },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'output-chat': {
    key: 'output-chat',
    title: 'Sportello Conversazionale',
    description: 'Assistenti, chatbot, UI.',
    primaryType: 'output',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Interfaccia Chat',
        type: 'output',
        footprint: { widthUnits: 4, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#E67D7D',
          border: '#9A3D3D',
          opacity: 0.95,
        },
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 2.5, heightUnits: 0.4 },
        offset: { x: 4.3, y: -0.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'output-public': {
    key: 'output-public',
    title: 'Output Pubblico / API',
    description: 'Portali cittadini, comunicati, servizi aperti.',
    primaryType: 'output',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Portale / API pubblica',
        type: 'output',
        footprint: { widthUnits: 4.2, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FB7185',
          border: '#9F1239',
          opacity: 0.95,
        },
      },
      {
        label: 'Messaggi ai cittadini',
        type: 'impact',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: {
          background: '#FECDD3',
          border: '#9F1239',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'impact-energy': {
    key: 'impact-energy',
    title: 'Consumo Energetico',
    description: 'Monitoraggio di energia e emissioni',
    primaryType: 'impact',
    primaryNodeIndex: 0,
    clusterLabel: 'Energia & Clima',
    nodes: [
      {
        label: 'Consumo Energetico Training',
        type: 'impact',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F59E0B',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'grid',
        },
      },
      {
        label: 'Emissioni CO2 Stimate',
        type: 'impact',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.9,
        },
      },
      {
        label: 'Energia Inferenza Real-time',
        type: 'impact',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FBBF24',
          border: '#D97706',
          opacity: 0.85,
        },
      },
      {
        label: 'Impronta Carbonio Infrastruttura',
        type: 'impact',
        footprint: { widthUnits: 5.2, heightUnits: 0.7 },
        offset: { x: 0, y: 3 },
        visual: {
          background: '#FDE047',
          border: '#CA8A04',
          opacity: 0.8,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
    ],
  },
  'impact-social': {
    key: 'impact-social',
    title: 'Impatto Sociale',
    description: 'Effetti su persone, lavoro e comunità',
    primaryType: 'impact',
    primaryNodeIndex: 0,
    clusterLabel: 'Impatto Sociale',
    nodes: [
      {
        label: 'Disparità di Accesso',
        type: 'impact',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F472B6',
          border: '#BE185D',
          opacity: 0.95,
          pattern: 'grid',
        },
      },
      {
        label: 'Sostituzione Lavoro Umano',
        type: 'impact',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FBCFE8',
          border: '#DB2777',
          opacity: 0.9,
        },
      },
      {
        label: 'Esclusione Digitale',
        type: 'impact',
        footprint: { widthUnits: 4.2, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#F9A8D4',
          border: '#EC4899',
          opacity: 0.85,
        },
      },
      {
        label: 'Impatto su Comunità Vulnerabili',
        type: 'impact',
        footprint: { widthUnits: 5, heightUnits: 0.7 },
        offset: { x: 0, y: 3 },
        visual: {
          background: '#FCE7F3',
          border: '#F472B6',
          opacity: 0.8,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
    ],
  },
  'impact-political': {
    key: 'impact-political',
    title: 'Impatto Politico',
    description: 'Governance, bias e fiducia pubblica',
    primaryType: 'impact',
    primaryNodeIndex: 0,
    clusterLabel: 'Impatto Politico',
    nodes: [
      {
        label: 'Bias Algoritmici',
        type: 'impact',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#94A3B8',
          border: '#475569',
          opacity: 0.95,
          pattern: 'grid',
        },
      },
      {
        label: 'Trasparenza Decisionale',
        type: 'impact',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#CBD5F5',
          border: '#475569',
          opacity: 0.9,
        },
      },
      {
        label: 'Accountability Pubblica',
        type: 'impact',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#E2E8F0',
          border: '#64748B',
          opacity: 0.85,
        },
      },
      {
        label: 'Fiducia dei Cittadini',
        type: 'impact',
        footprint: { widthUnits: 4.2, heightUnits: 0.7 },
        offset: { x: 0, y: 3 },
        visual: {
          background: '#F1F5F9',
          border: '#94A3B8',
          opacity: 0.8,
        },
      },
      {
        label: 'Influenza su Policy Pubbliche',
        type: 'impact',
        footprint: { widthUnits: 5, heightUnits: 0.7 },
        offset: { x: 0, y: 4 },
        visual: {
          background: '#CBD5E1',
          border: '#64748B',
          opacity: 0.75,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
    ],
  },
  'risk-compliance': {
    key: 'risk-compliance',
    title: 'Policy & Compliance',
    description: 'Audit interni, DPIA, linee guida.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Compliance & Policy',
    nodes: [
      {
        label: 'DPIA (Data Protection Impact Assessment)',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Audit Trail Completo',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Linee Guida Legali',
        type: 'risk',
        footprint: { widthUnits: 4.2, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
      },
      {
        label: 'Revisioni Periodiche',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.7 },
        offset: { x: 0, y: 3 },
        visual: {
          background: '#FFFBEB',
          border: '#FCD34D',
          opacity: 0.8,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
    ],
  },
  'risk-transfer': {
    key: 'risk-transfer',
    title: 'Supervisione Transfer',
    description: 'Controllo trasferimenti extra-UE.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    exposed: false,
    nodes: [
      {
        label: 'Supervisione Transfer',
        type: 'risk',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F2C7C7',
          border: '#BF7373',
          opacity: 0.9,
        },
      },
    ],
  },
  'risk-oversight': {
    key: 'risk-oversight',
    title: 'Oversight Board',
    description: 'Comitato etico / DPO.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Supervisione Umana',
    nodes: [
      {
        label: 'Comitato Etico',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F5E5C7',
          border: '#C9A877',
          opacity: 0.95,
        },
      },
      {
        label: 'DPO (Data Protection Officer)',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Human-in-the-Loop',
        type: 'risk',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
        config: { humanInTheLoop: true },
      },
      {
        label: 'Review Decisioni Critiche',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 3 },
        visual: {
          background: '#FFFBEB',
          border: '#FCD34D',
          opacity: 0.8,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
    ],
  },
  'input-health': {
    key: 'input-health',
    title: 'Dati Sanitari',
    description: 'Cartelle cliniche, dati medici, dispositivi medici.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Sanitari',
    nodes: [
      {
        label: 'Dati Sanitari',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#DC2626',
          border: '#991B1B',
          pattern: 'grid',
          opacity: 0.95,
        },
        config: { dataTypes: ['Sanitari', 'Categoria Speciale GDPR'] },
      },
      {
        label: 'Consenso Esplicito',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.6 },
        offset: { x: 0.2, y: 1.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-financial': {
    key: 'input-financial',
    title: 'Dati Finanziari',
    description: 'Informazioni bancarie, transazioni, credit scoring.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Finanziari',
    nodes: [
      {
        label: 'Dati Finanziari',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#059669',
          border: '#047857',
          pattern: 'grid',
          opacity: 0.95,
        },
        config: { dataTypes: ['Finanziari', 'Sensibili'] },
      },
      {
        label: 'Sicurezza Rafforzata',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.6 },
        offset: { x: 0.2, y: 1.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-location': {
    key: 'input-location',
    title: 'Dati di Localizzazione',
    description: 'GPS, geolocalizzazione, tracciamento posizione.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Localizzazione',
    nodes: [
      {
        label: 'Dati di Localizzazione',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#7C3AED',
          border: '#5B21B6',
          pattern: 'grid',
          opacity: 0.95,
        },
        config: { dataTypes: ['Geolocalizzazione'] },
      },
      {
        label: 'Minimizzazione Posizione',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.6 },
        offset: { x: 0.2, y: 1.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-vision': {
    key: 'process-vision',
    title: 'Analisi Immagini e Video',
    description: 'Riconoscimento oggetti, scene, qualità immagini.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Computer Vision',
        type: 'process',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#8B5CF6'),
      },
      {
        label: 'Validazione Qualità',
        type: 'risk',
        footprint: { widthUnits: 3, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'output-notification': {
    key: 'output-notification',
    title: 'Notifiche e Alert',
    description: 'Comunicazioni automatiche, avvisi, messaggi.',
    primaryType: 'output',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Sistema di Notifiche',
        type: 'output',
        footprint: { widthUnits: 4.2, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F59E0B',
          border: '#D97706',
          opacity: 0.95,
        },
      },
      {
        label: 'Preferenze Utente',
        type: 'risk',
        footprint: { widthUnits: 3.5, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'output-dashboard': {
    key: 'output-dashboard',
    title: 'Dashboard Analitiche',
    description: 'Visualizzazioni dati, metriche, indicatori di performance.',
    primaryType: 'output',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Dashboard Analitica',
        type: 'output',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#10B981',
          border: '#059669',
          opacity: 0.95,
        },
      },
      {
        label: 'Accesso Controllato',
        type: 'risk',
        footprint: { widthUnits: 3.5, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'risk-security': {
    key: 'risk-security',
    title: 'Sicurezza Informatica',
    description: 'Crittografia, protezione accessi, rilevamento intrusioni.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Sicurezza',
    nodes: [
      {
        label: 'Crittografia Dati',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Controllo Accessi',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Monitoraggio Intrusioni',
        type: 'risk',
        footprint: { widthUnits: 4.2, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
    ],
  },
  'risk-retention': {
    key: 'risk-retention',
    title: 'Conservazione e Cancellazione',
    description: 'Politiche di retention, diritto all\'oblio, cancellazione automatica.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Retention',
    nodes: [
      {
        label: 'Politica di Retention',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Diritto all\'Oblio',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Cancellazione Automatica',
        type: 'risk',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
    ],
  },
  'risk-privacy': {
    key: 'risk-privacy',
    title: 'Privacy by Design',
    description: 'Minimizzazione dati, pseudonimizzazione, anonimizzazione.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Privacy Design',
    nodes: [
      {
        label: 'Minimizzazione Dati',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Pseudonimizzazione',
        type: 'risk',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Anonimizzazione',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
    ],
  },
  'risk-access': {
    key: 'risk-access',
    title: 'Controllo Accessi e Audit',
    description: 'Chi può accedere, log accessi, tracciabilità operazioni.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Access Control',
    nodes: [
      {
        label: 'Gestione Permessi',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Log Accessi',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Tracciabilità Operazioni',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
    ],
  },
  'input-behavioral': {
    key: 'input-behavioral',
    title: 'Dati Comportamentali',
    description: 'Navigazione web, preferenze utente, profili comportamentali.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Comportamentali',
    nodes: [
      {
        label: 'Dati Comportamentali',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#8B5CF6',
          border: '#6D28D9',
          pattern: 'grid',
          opacity: 0.95,
        },
        config: { dataTypes: ['Comportamentali', 'Preferenze'] },
      },
      {
        label: 'Gestione Cookie',
        type: 'risk',
        footprint: { widthUnits: 3.5, heightUnits: 0.6 },
        offset: { x: 0.2, y: 1.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-audio': {
    key: 'input-audio',
    title: 'Dati Audio',
    description: 'Registrazioni vocali, call center, assistenti vocali.',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Audio',
    nodes: [
      {
        label: 'Registrazioni Audio',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#EC4899',
          border: '#BE185D',
          pattern: 'grid',
          opacity: 0.95,
        },
        config: { dataTypes: ['Audio', 'Vocali'] },
      },
      {
        label: 'Consenso Registrazione',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: 0.2, y: 1.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-recommendation': {
    key: 'process-recommendation',
    title: 'Sistemi di Raccomandazione',
    description: 'Suggerimenti personalizzati, filtri, ranking.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Sistema di Raccomandazione',
        type: 'process',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#A855F7'),
      },
      {
        label: 'Filtro Bias',
        type: 'risk',
        footprint: { widthUnits: 3.5, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-anomaly': {
    key: 'process-anomaly',
    title: 'Rilevamento Anomalie',
    description: 'Identificazione pattern anomali, fraud detection, sicurezza.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Rilevamento Anomalie',
        type: 'process',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#EF4444'),
      },
      {
        label: 'Validazione Alert',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'process-audio': {
    key: 'process-audio',
    title: 'Elaborazione Audio',
    description: 'Speech-to-text, analisi vocale, sentiment analysis audio.',
    primaryType: 'process',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Elaborazione Audio',
        type: 'process',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#EC4899'),
      },
      {
        label: 'Trascrizione Sicura',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'output-export': {
    key: 'output-export',
    title: 'Export e Integrazioni',
    description: 'Esportazione dati, connessioni con altri sistemi, API esterne.',
    primaryType: 'output',
    primaryNodeIndex: 0,
    nodes: [
      {
        label: 'Export Dati',
        type: 'output',
        footprint: { widthUnits: 4.2, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Controllo Trasferimenti',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: 0.2, y: 0.9 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'risk-backup': {
    key: 'risk-backup',
    title: 'Backup e Ripristino',
    description: 'Copie di sicurezza, continuità operativa, disaster recovery.',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Backup & Recovery',
    nodes: [
      {
        label: 'Backup Automatico',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#FCD34D',
          border: '#B45309',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Disaster Recovery',
        type: 'risk',
        footprint: { widthUnits: 4.8, heightUnits: 0.7 },
        offset: { x: 0, y: 1 },
        visual: {
          background: '#FDE68A',
          border: '#D97706',
          opacity: 0.9,
        },
      },
      {
        label: 'Piano Continuità',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.7 },
        offset: { x: 0, y: 2 },
        visual: {
          background: '#FEF3C7',
          border: '#F59E0B',
          opacity: 0.85,
        },
      },
    ],
    localConnections: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
    ],
  },

  // ========== BLUEPRINTS PER UTENTI FINALI (mode: 'use') ==========
  
  // --- Strumenti AI usati ---
  'use-chatgpt': {
    key: 'use-chatgpt',
    title: 'ChatGPT',
    description: 'Uso ChatGPT per lavorare',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'ChatGPT',
    nodes: [
      {
        label: 'ChatGPT',
        type: 'process',
        footprint: { widthUnits: 4, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#10A37F'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-gemini': {
    key: 'use-gemini',
    title: 'Google Gemini',
    description: 'Uso Gemini per lavorare',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Gemini',
    nodes: [
      {
        label: 'Google Gemini',
        type: 'process',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#4285F4'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-claude': {
    key: 'use-claude',
    title: 'Claude (Anthropic)',
    description: 'Uso Claude per lavorare',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Claude',
    nodes: [
      {
        label: 'Claude',
        type: 'process',
        footprint: { widthUnits: 4, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#D97757'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-copilot': {
    key: 'use-copilot',
    title: 'Copilot',
    description: 'Uso Copilot per lavorare',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Copilot',
    nodes: [
      {
        label: 'Copilot',
        type: 'process',
        footprint: { widthUnits: 4, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#238636'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-midjourney': {
    key: 'use-midjourney',
    title: 'Midjourney / DALL-E',
    description: 'Uso strumenti AI per immagini',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'AI Immagini',
    nodes: [
      {
        label: 'Generazione Immagini AI',
        type: 'process',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#FF6B9D'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-translation': {
    key: 'use-translation',
    title: 'Traduzione Automatica',
    description: 'Uso AI per tradurre',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Traduzione AI',
    nodes: [
      {
        label: 'Traduzione Automatica',
        type: 'process',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#4285F4'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-voice': {
    key: 'use-voice',
    title: 'Assistenti Vocali',
    description: 'Uso assistenti vocali AI',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Assistente Vocale',
    nodes: [
      {
        label: 'Assistente Vocale AI',
        type: 'process',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#FF9500'),
      },
      {
        label: 'Consenso Registrazione',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-other': {
    key: 'use-other',
    title: 'Altro Strumento AI',
    description: 'Uso altro strumento AI',
    primaryType: 'process',
    primaryNodeIndex: 0,
    clusterLabel: 'Strumento AI',
    nodes: [
      {
        label: 'Strumento AI',
        type: 'process',
        footprint: { widthUnits: 4, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: darkProcessVisual('#8B5CF6'),
      },
      {
        label: 'Notifier Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },

  // --- Casi d'uso ---
  'use-case-email': {
    key: 'use-case-email',
    title: 'Scrivere Email',
    description: 'Uso AI per scrivere email',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Email',
    nodes: [
      {
        label: 'Email Scritta',
        type: 'output',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Privacy by Design',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-case-documents': {
    key: 'use-case-documents',
    title: 'Analizzare Documenti',
    description: 'Uso AI per analizzare documenti',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Documenti',
    nodes: [
      {
        label: 'Documenti Analizzati',
        type: 'output',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Sicurezza Informatica',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-case-code': {
    key: 'use-case-code',
    title: 'Scrivere Codice',
    description: 'Uso AI per programmare',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Codice',
    nodes: [
      {
        label: 'Codice Generato',
        type: 'output',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Licenze & Attribution',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-case-research': {
    key: 'use-case-research',
    title: 'Fare Ricerche',
    description: 'Uso AI per cercare informazioni',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Ricerca',
    nodes: [
      {
        label: 'Risultati Ricerca',
        type: 'output',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Dataset Ombra',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-case-creative': {
    key: 'use-case-creative',
    title: 'Creare Contenuti',
    description: 'Uso AI per generare contenuti',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Contenuti',
    nodes: [
      {
        label: 'Contenuti Creati',
        type: 'output',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Licenze & Attribution',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.5 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-case-meetings': {
    key: 'use-case-meetings',
    title: 'Trascrivere Riunioni',
    description: 'Uso AI per trascrizioni',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Trascrizioni',
    nodes: [
      {
        label: 'Trascrizioni',
        type: 'output',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Trascrizione Sicura',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },

  // --- Tipo di dati condivisi ---
  'input-work': {
    key: 'input-work',
    title: 'Dati di Lavoro',
    description: 'Condivido informazioni di lavoro',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Lavoro',
    nodes: [
      {
        label: 'Dati di Lavoro',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#5E8B4B',
          border: '#314A25',
          opacity: 0.95,
          pattern: 'grid',
        },
        config: { dataTypes: ['Identificativi'] },
      },
      {
        label: 'Perimetro Consenso',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.5, y: 1.2 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-personal-user': {
    key: 'input-personal-user',
    title: 'Dati Personali',
    description: 'Condivido i miei dati personali',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Personali',
    nodes: [
      {
        label: 'I Miei Dati Personali',
        type: 'input',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#5E8B4B',
          border: '#314A25',
          opacity: 0.95,
          pattern: 'grid',
        },
        config: { dataTypes: ['Identificativi'] },
      },
      {
        label: 'Perimetro Consenso',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1.2 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-sensitive': {
    key: 'input-sensitive',
    title: 'Informazioni Sensibili',
    description: 'Condivido dati sensibili',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Sensibili',
    nodes: [
      {
        label: 'Dati Sensibili',
        type: 'input',
        footprint: { widthUnits: 4.5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#B91C1C',
          border: '#991B1B',
          opacity: 0.95,
          pattern: 'grid',
        },
        config: { dataTypes: ['Biometrici', 'Sanitari', 'Finanziari'] },
      },
      {
        label: 'Consenso Esplicito',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1.2 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-others': {
    key: 'input-others',
    title: 'Dati di Altri',
    description: 'Condivido dati di altre persone',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Terzi',
    nodes: [
      {
        label: 'Dati di Altre Persone',
        type: 'input',
        footprint: { widthUnits: 5, heightUnits: 0.9 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#DC2626',
          border: '#991B1B',
          opacity: 0.95,
          pattern: 'grid',
        },
        config: { dataTypes: ['Identificativi'] },
      },
      {
        label: 'Perimetro Consenso',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1.2 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },

  // --- Storage per utenti ---
  'storage-cloud-usa': {
    key: 'storage-cloud-usa',
    title: 'Server USA',
    description: 'I dati finiscono su server americani',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    clusterLabel: 'Cloud USA',
    nodes: [
      {
        label: 'Cloud Server (USA)',
        type: 'storage',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#EF4444',
          border: '#DC2626',
          opacity: 0.95,
        },
      },
      {
        label: 'Supervisione Transfer',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'storage-cloud-eu': {
    key: 'storage-cloud-eu',
    title: 'Server Europa',
    description: 'I dati sono salvati in Europa',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    clusterLabel: 'Cloud EU',
    nodes: [
      {
        label: 'Cloud Server (EU)',
        type: 'storage',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#10B981',
          border: '#059669',
          opacity: 0.95,
        },
      },
      {
        label: 'Sicurezza Informatica',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'storage-cloud-unknown': {
    key: 'storage-cloud-unknown',
    title: 'Non So Dove',
    description: 'Non so dove vengono salvati i dati',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    clusterLabel: 'Storage Sconosciuto',
    nodes: [
      {
        label: 'Storage Sconosciuto',
        type: 'storage',
        footprint: { widthUnits: 5.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F59E0B',
          border: '#D97706',
          opacity: 0.95,
        },
      },
      {
        label: 'Supervisione Transfer',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: perimeterVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'storage-local-user': {
    key: 'storage-local-user',
    title: 'Solo Sul Mio Computer',
    description: 'Dati salvati solo localmente',
    primaryType: 'storage',
    primaryNodeIndex: 0,
    clusterLabel: 'Storage Locale',
    nodes: [
      {
        label: 'Sul Mio Computer',
        type: 'storage',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Backup e Ripristino',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: 0.2, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },

  // --- Rischi per utenti ---
  'risk-privacy-user': {
    key: 'risk-privacy-user',
    title: 'Privacy Dati Personali',
    description: 'Preoccupato per la privacy',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Rischio Privacy',
    nodes: [
      {
        label: 'Privacy Dati',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#EF4444',
          border: '#DC2626',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Privacy by Design',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'risk-work': {
    key: 'risk-work',
    title: 'Esposizione Dati Lavoro',
    description: 'Preoccupato per dati di lavoro',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Rischio Lavoro',
    nodes: [
      {
        label: 'Esposizione Dati Lavoro',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F59E0B',
          border: '#D97706',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Sicurezza Informatica',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'risk-bias-user': {
    key: 'risk-bias-user',
    title: 'Discriminazione',
    description: 'Preoccupato di essere discriminato',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Rischio Bias',
    nodes: [
      {
        label: 'Rischio Discriminazione',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#DC2626',
          border: '#991B1B',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Filtro Bias',
        type: 'risk',
        footprint: { widthUnits: 4, heightUnits: 0.5 },
        offset: { x: 0.2, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'risk-decisions': {
    key: 'risk-decisions',
    title: 'Decisioni Automatiche',
    description: 'Preoccupato per decisioni automatiche',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Rischio Decisioni',
    nodes: [
      {
        label: 'Decisioni Automatiche',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#DC2626',
          border: '#991B1B',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Supervisione Umana',
        type: 'risk',
        footprint: { widthUnits: 5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'risk-transparency': {
    key: 'risk-transparency',
    title: 'Trasparenza',
    description: 'Non capisco cosa fa il sistema',
    primaryType: 'risk',
    primaryNodeIndex: 0,
    clusterLabel: 'Rischio Trasparenza',
    nodes: [
      {
        label: 'Mancanza Trasparenza',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#F59E0B',
          border: '#D97706',
          opacity: 0.95,
          pattern: 'perimeter',
        },
      },
      {
        label: 'Trasparenza Decisionale',
        type: 'risk',
        footprint: { widthUnits: 5.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  
  // --- Blueprint mancanti per utenti finali ---
  'use-case-translation-case': {
    key: 'use-case-translation-case',
    title: 'Tradurre Testi',
    description: 'Uso AI per tradurre',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Traduzione',
    nodes: [
      {
        label: 'Testi Tradotti',
        type: 'output',
        footprint: { widthUnits: 4.5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Privacy by Design',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'use-case-personal': {
    key: 'use-case-personal',
    title: 'Uso Personale',
    description: 'Uso AI per hobby o curiosità',
    primaryType: 'output',
    primaryNodeIndex: 0,
    clusterLabel: 'Uso Personale',
    nodes: [
      {
        label: 'Contenuto Personale',
        type: 'output',
        footprint: { widthUnits: 5, heightUnits: 0.8 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#6366F1',
          border: '#4F46E5',
          opacity: 0.95,
        },
      },
      {
        label: 'Privacy by Design',
        type: 'risk',
        footprint: { widthUnits: 4.5, heightUnits: 0.6 },
        offset: { x: -0.25, y: 1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
  'input-public-user': {
    key: 'input-public-user',
    title: 'Solo Dati Pubblici',
    description: 'Uso solo informazioni pubbliche',
    primaryType: 'input',
    primaryNodeIndex: 0,
    clusterLabel: 'Dati Pubblici',
    nodes: [
      {
        label: 'Dati Pubblici',
        type: 'input',
        footprint: { widthUnits: 4, heightUnits: 0.7 },
        offset: { x: 0, y: 0 },
        visual: {
          background: '#73A560',
          border: '#406230',
          pattern: 'grid',
          opacity: 0.9,
        },
      },
      {
        label: 'Licenze & Attribution',
        type: 'risk',
        footprint: { widthUnits: 2.5, heightUnits: 0.45 },
        offset: { x: 4.1, y: -0.1 },
        visual: riskChipVisual,
      },
    ],
    localConnections: [{ from: 0, to: 1 }],
  },
};

type CityAction = {
  key: string;
  title: string;
  description: string;
};

export type CityActionGroup = {
  label: string;
  actions: CityAction[];
};

export const CITY_ACTION_GROUPS: CityActionGroup[] = [
  {
    label: 'DOMANDA: Che tipo di informazioni raccogli?',
    actions: [
      { key: 'input-personal', title: 'Dati delle persone', description: 'Informazioni su clienti, cittadini o utenti: nomi, email, indirizzi, numeri di telefono, dati anagrafici.' },
      { key: 'input-video', title: 'Video e riconoscimento biometrico', description: 'Riprese video, foto per riconoscimento facciale, impronte digitali, scansioni corporee.' },
      { key: 'input-location', title: 'Dati di localizzazione', description: 'Posizione GPS, geolocalizzazione, tracciamento spostamenti, dati di movimento.' },
      { key: 'input-behavioral', title: 'Dati comportamentali', description: 'Come le persone navigano su internet, cosa preferiscono, profili di comportamento e interessi.' },
      { key: 'input-audio', title: 'Registrazioni audio', description: 'Registrazioni di chiamate, conversazioni vocali, assistenti vocali, call center.' },
      { key: 'input-public', title: 'Dati pubblici e informazioni dal web', description: 'Dati aperti, informazioni da siti web, social network, notizie online.' },
      { key: 'input-operational', title: 'Dati tecnici e sensori', description: 'Informazioni da macchinari, dispositivi connessi, sensori, log di sistema.' },
      { key: 'input-partner', title: 'Dati da altre aziende', description: 'Informazioni acquistate o ricevute da fornitori esterni, altre organizzazioni.' },
    ],
  },
  {
    label: 'DOMANDA: Raccogli dati sanitari o finanziari?',
    actions: [
      { key: 'input-health', title: 'Dati sanitari', description: 'Cartelle cliniche, dati medici, informazioni su salute e malattie, dispositivi medici connessi.' },
      { key: 'input-financial', title: 'Dati finanziari', description: 'Informazioni bancarie, conti correnti, transazioni, dati di pagamento, credit scoring.' },
    ],
  },
  {
    label: 'DOMANDA: Come funziona il sistema che usi?',
    actions: [
      { key: 'process-llm', title: 'Chatbot che risponde alle domande', description: 'Sistemi che rispondono a domande, generano testi, conversano come ChatGPT.' },
      { key: 'process-rag', title: 'Ricerca intelligente nei documenti', description: 'Sistemi che cercano informazioni in grandi archivi di documenti e rispondono a domande specifiche.' },
      { key: 'process-automation', title: 'Calcoli e classificazioni automatiche', description: 'Sistemi che applicano regole predefinite, calcolano punteggi o classificano automaticamente.' },
      { key: 'process-modelops', title: 'Sistema che impara da esempi', description: 'Sistemi che imparano da esempi per migliorare le loro prestazioni nel tempo.' },
    ],
  },
  {
    label: 'DOMANDA: Analizzi immagini, video o audio?',
    actions: [
      { key: 'process-biometric', title: 'Riconoscimento di identità', description: 'Sistemi che identificano persone attraverso volti, impronte o altre caratteristiche fisiche.' },
      { key: 'process-vision', title: 'Analisi immagini e video', description: 'Sistemi che riconoscono oggetti, scene, qualità delle immagini, analisi di contenuti visivi.' },
      { key: 'process-audio', title: 'Elaborazione audio e voce', description: 'Sistemi che trasformano la voce in testo, analizzano il tono e le emozioni nelle registrazioni vocali.' },
    ],
  },
  {
    label: 'DOMANDA: Il sistema suggerisce o rileva anomalie?',
    actions: [
      { key: 'process-recommendation', title: 'Sistemi di raccomandazione', description: 'Sistemi che suggeriscono prodotti, contenuti o azioni personalizzate basate sulle preferenze.' },
      { key: 'process-anomaly', title: 'Rilevamento anomalie e frodi', description: 'Sistemi che identificano comportamenti sospetti, transazioni anomale o tentativi di frode.' },
    ],
  },
  {
    label: 'DOMANDA: Dove conservi i dati?',
    actions: [
      { key: 'storage-eu', title: 'Server in Europa', description: 'I dati vengono salvati su computer e server situati in paesi dell\'Unione Europea.' },
      { key: 'storage-us', title: 'Server fuori dall\'Europa', description: 'I dati vengono salvati o trasferiti su server situati in paesi al di fuori dell\'Unione Europea.' },
      { key: 'storage-onprem', title: 'Server propri o dispositivi locali', description: 'I dati vengono salvati su computer di proprietà dell\'organizzazione o su dispositivi sul campo.' },
    ],
  },
  {
    label: 'DOMANDA: Come vengono utilizzati i risultati?',
    actions: [
      { key: 'output-decision', title: 'Decisioni automatiche', description: 'Il sistema prende decisioni in modo automatico, ad esempio approva o rifiuta una richiesta.' },
      { key: 'output-chat', title: 'Interfaccia di chat o report', description: 'Le informazioni vengono mostrate tramite chat, documenti o dashboard per essere consultate.' },
      { key: 'output-notification', title: 'Notifiche e avvisi automatici', description: 'Il sistema invia messaggi, email o notifiche push per comunicare risultati o avvisi.' },
      { key: 'output-dashboard', title: 'Dashboard analitiche', description: 'Visualizzazioni grafiche dei dati, statistiche, indicatori di performance e metriche.' },
      { key: 'output-export', title: 'Export e integrazioni con altri sistemi', description: 'Esportazione dei dati, connessioni con altri software o organizzazioni tramite interfacce tecniche.' },
      { key: 'output-public', title: 'Servizi pubblici o API', description: 'Le informazioni vengono pubblicate su portali pubblici o condivise con altre organizzazioni tramite interfacce tecniche.' },
    ],
  },
  {
    label: 'DOMANDA: Chi può vedere i tuoi dati e come sono protetti?',
    actions: [
      { key: 'risk-security', title: 'Dati protetti (cifrati)', description: 'I dati sono protetti come in una cassaforte: solo chi ha la chiave può leggerli. Protezione contro tentativi di furto.' },
      { key: 'risk-access', title: 'Controllo di chi accede', description: 'Solo alcune persone possono vedere i dati. Viene registrato chi accede, quando e cosa fa.' },
      { key: 'risk-retention', title: 'Dati cancellati automaticamente', description: 'I dati vengono conservati solo per il tempo necessario e poi cancellati automaticamente. Hai diritto a chiederne la cancellazione.' },
      { key: 'risk-privacy', title: 'Raccolta minima e dati anonimi', description: 'Vengono raccolti solo i dati necessari. I dati sensibili vengono resi difficili da identificare (anonimizzati).' },
      { key: 'risk-backup', title: 'Copie di sicurezza', description: 'Ci sono copie di sicurezza dei dati. Cosa succede se i dati vengono persi? Come vengono ripristinati?' },
    ],
  },
  {
    label: 'DOMANDA: Quali rischi ti preoccupano di più?',
    actions: [
      { key: 'impact-energy', title: 'Consumo di energia e impatto ambientale', description: 'Quanta energia elettrica usa il sistema e quali sono le emissioni di anidride carbonica prodotte.' },
      { key: 'impact-social', title: 'Esclusione o discriminazione', description: 'Il sistema funziona per tutti o esclude alcune persone? Effetti su posti di lavoro e accessibilità.' },
      { key: 'impact-political', title: 'Fiducia e trasparenza', description: 'Come viene costruita la fiducia? Le decisioni sono trasparenti? Ci sono pregiudizi nascosti nel sistema?' },
      { key: 'risk-oversight', title: 'Controllo umano delle decisioni', description: 'C\'è sempre qualcuno che controlla le decisioni del sistema? Puoi chiedere una revisione umana?' },
      { key: 'risk-compliance', title: 'Conformità alle leggi', description: 'Il sistema rispetta le leggi (GDPR, AI Act)? Viene verificato regolarmente?' },
    ],
  },
];

export const DEFAULT_BLUEPRINT_FOR_TYPE: Partial<Record<ScenarioBlock['type'], string>> = {
  input: 'input-personal',
  process: 'process-llm',
  storage: 'storage-eu',
  output: 'output-decision',
  risk: 'risk-oversight',
  impact: 'impact-energy',
};

// Domande per UTENTI FINALI (chi usa AI, non chi la progetta)
export const CITY_ACTION_GROUPS_USER: CityActionGroup[] = [
  {
    label: 'DOMANDA: Quale strumento AI stai usando?',
    actions: [
      { key: 'use-chatgpt', title: 'ChatGPT', description: 'Uso ChatGPT per scrivere email, testi, risposte o generare contenuti.' },
      { key: 'use-gemini', title: 'Google Gemini', description: 'Uso Gemini per analizzare documenti, rispondere domande o generare contenuti.' },
      { key: 'use-claude', title: 'Claude (Anthropic)', description: 'Uso Claude per lavorare con documenti, codici o conversazioni complesse.' },
      { key: 'use-copilot', title: 'GitHub Copilot / Microsoft Copilot', description: 'Uso Copilot per scrivere codice o generare contenuti in Microsoft 365.' },
      { key: 'use-midjourney', title: 'Midjourney / DALL-E', description: 'Uso strumenti AI per generare immagini, foto o arte.' },
      { key: 'use-translation', title: 'Traduzione automatica', description: 'Uso strumenti AI per tradurre testi o conversazioni.' },
      { key: 'use-voice', title: 'Assistenti vocali AI', description: 'Uso Alexa, Siri, Google Assistant o altri assistenti vocali.' },
      { key: 'use-other', title: 'Altro strumento AI', description: 'Uso altri strumenti di intelligenza artificiale non elencati qui.' },
    ],
  },
  {
    label: 'DOMANDA: Per cosa lo usi?',
    actions: [
      { key: 'use-case-email', title: 'Scrivere email e messaggi', description: 'Uso AI per aiutarmi a scrivere email professionali o personali.' },
      { key: 'use-case-documents', title: 'Analizzare o revisionare documenti', description: 'Uso AI per leggere, riassumere o correggere documenti aziendali.' },
      { key: 'use-case-code', title: 'Scrivere codice', description: 'Uso AI per aiutarmi a programmare o debuggare codice.' },
      { key: 'use-case-research', title: 'Fare ricerche e informazioni', description: 'Uso AI per cercare informazioni, rispondere a domande o studiare.' },
      { key: 'use-case-creative', title: 'Creare contenuti (testi, immagini)', description: 'Uso AI per generare testi creativi, immagini o altri contenuti.' },
      { key: 'use-case-translation-case', title: 'Tradurre testi o comunicare', description: 'Uso AI per tradurre lingue o comunicare con persone di altre lingue.' },
      { key: 'use-case-meetings', title: 'Trascrivere o riassumere riunioni', description: 'Uso AI per trascrivere chiamate, riunioni o generare riassunti.' },
      { key: 'use-case-personal', title: 'Uso personale e hobby', description: 'Uso AI per attività personali, hobby o curiosità.' },
    ],
  },
  {
    label: 'DOMANDA: Che tipo di informazioni condividi?',
    actions: [
      { key: 'input-work', title: 'Informazioni di lavoro', description: 'Condivido dati aziendali, documenti professionali, informazioni su clienti o colleghi.' },
      { key: 'input-personal-user', title: 'Dati personali', description: 'Condivido il mio nome, email, indirizzo o altre informazioni personali.' },
      { key: 'input-sensitive', title: 'Informazioni sensibili', description: 'Condivido dati sanitari, finanziari, password o informazioni molto private.' },
      { key: 'input-others', title: 'Dati di altre persone', description: 'Condivido informazioni su clienti, colleghi, amici o familiari.' },
      { key: 'input-public-user', title: 'Solo informazioni pubbliche', description: 'Uso solo informazioni già pubbliche o generali, nessun dato personale.' },
    ],
  },
  {
    label: 'DOMANDA: Dove viene salvato quello che condividi?',
    actions: [
      { key: 'storage-cloud-usa', title: 'Su server americani (Stati Uniti)', description: 'Lo strumento salva i dati su server negli USA (es. ChatGPT, Gemini).' },
      { key: 'storage-cloud-eu', title: 'Su server europei', description: 'I dati vengono salvati in Europa (più protetto dalle leggi GDPR).' },
      { key: 'storage-cloud-unknown', title: 'Non lo so / Non l\'ho controllato', description: 'Non ho verificato dove vengono salvati i dati.' },
      { key: 'storage-local-user', title: 'Solo sul mio computer/dispositivo', description: 'Uso strumenti locali che non inviano dati su internet.' },
    ],
  },
  {
    label: 'DOMANDA: Quali rischi ti preoccupano di più?',
    actions: [
      { key: 'risk-privacy-user', title: 'I miei dati personali rubati o usati male', description: 'Temo che i miei dati vengano rubati, venduti o usati senza il mio consenso.' },
      { key: 'risk-work', title: 'Informazioni di lavoro esposte', description: 'Preoccupato che dati aziendali o informazioni confidenziali finiscano nelle mani sbagliate.' },
      { key: 'risk-bias-user', title: 'Essere discriminato o escluso', description: 'Preoccupato che il sistema possa prendere decisioni ingiuste o discriminatorie su di me.' },
      { key: 'risk-decisions', title: 'Decisioni automatiche sbagliate su di me', description: 'Temo che il sistema prenda decisioni importanti per me senza che possa controllarle.' },
      { key: 'risk-transparency', title: 'Non capire cosa fa il sistema', description: 'Preoccupato di non capire come funziona e perché fa certe scelte.' },
    ],
  },
];

